name: Portfolio-V2
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=local
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - default

  payload:
    image: node:18-alpine
    ports:
      - 3001:3001
    volumes:
      - ./payload-cms:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev --port 3001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URI=postgres://local:local@postgres:5432/local
      - PAYLOAD_SECRET=secret
    env_file:
      - .env
    networks:
      - default

  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - payload
      - postgres
    networks:
      - default

  frontend-prod:
    build:
      dockerfile: ./frontend/Dockerfile.prod
      context: .
      network: host
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - payload

networks:
  default:
    name: portfolio-v2-network
