name: Portfolio-V2
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=local
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data

  payload:
    image: node:18-alpine
    ports:
      - 3001:3001
    volumes:
      - ./payload-cms:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev --port 3001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URI=postgres://local:local@postgres:5432/local
      - PAYLOAD_SECRET=44632985494f2c30d88b7ee4
    env_file:
      - .env

  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
