name: Portfolio-V2
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=local
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local"]
      interval: 30s
      timeout: 10s
      retries: 3

  payload:
    image: node:18-alpine
    ports:
      - 3000:3000
    volumes:
      - ./payload-cms:/home/node/app
      - /home/node/app/node_modules
    working_dir: /home/node/app
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URI=postgres://local:local@postgres:5432/local
      - PAYLOAD_SECRET=44632985494f2c30d88b7ee4
    env_file:
      - .env
